# Generated by Django 3.1.7 on 2021-05-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20210501_2109'),
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenplant',
            name='plant',
        ),
        migrations.AddField(
            model_name='gardenplant',
            name='plant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='plants.plant'),
        ),
    ]
